/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TEA */

#ifndef _Included_TEA
#define _Included_TEA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TEA
 * Method:    nativeEncrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_TEA_nativeEncrypt
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     TEA
 * Method:    nativeDecrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_TEA_nativeDecrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
